server.port=8000

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@stoxle_low?TNS_ADMIN=C:/oraclepw
spring.datasource.username=ADMIN
spring.datasource.password=Heeyoun1220!
oracle.net.wallet_location=(SOURCE=(METHOD=FILE)(METHOD_DATA=(DIRECTORY=C:/oraclepw)))

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2


spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


# ?????? API
kis.api.app-key=${KIS_APP_KEY}
kis.api.app-secret=${KIS_APP_SECRET}
kis.api.base-url=${KIS_BASE_URL}

# python ??
python.path=C:/Users/edu_)_/Documents/GitHub/stock/.venv/Scripts/python.exe

# ?? API ?? (??? ??)
asset.prediction.api-url=http://127.0.0.1:9000/api/asset/predict

