# 1. ???? ??
spring.application.name=demo

# 2. ??? ???? DB ?? (??? / ?? ? ??!)
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# spring.datasource.url=jdbc:oracle:thin:@stoxle_high?TNS_ADMIN=C:/oraclepw
spring.datasource.url=jdbc:oracle:thin:@stoxle_low?TNS_ADMIN=C:/oraclepw
spring.datasource.username=ADMIN
spring.datasource.password=Heeyoun1220!

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1

# 3. JPA ? ?????? ?? (??? ???)
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# 4. ???? ?? ?? ?? ?? ?? (?? ??? cwallet.sso? ????)
oracle.net.wallet_location=(SOURCE=(METHOD=FILE)(METHOD_DATA=(DIRECTORY=C:/oraclepw)))


# ?????? API
kis.api.app-key=${KIS_APP_KEY}
kis.api.app-secret=${KIS_APP_SECRET}
kis.api.base-url=${KIS_BASE_URL}


# python ??
python.path=C:/Users/edu_)_/Documents/GitHub/stock/.venv/Scripts/python.exe
