# 1. ???? ??
spring.application.name=demo

# 2. ??? ???? DB ?? (??? / ?? ? ??!)
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@stoxle_high?TNS_ADMIN=C:/oraclepw
#spring.datasource.username=ADMIN
#spring.datasource.password=Heeyoun1220!

# 3. JPA ? ?????? ?? (??? ???)
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none

# 4. ???? ?? ?? ?? ?? ?? (?? ??? cwallet.sso? ????)
oracle.net.wallet_location=(SOURCE=(METHOD=FILE)(METHOD_DATA=(DIRECTORY=C:/oraclepw)))

# ?????? API
kis.api.app-key=PS8sRbbSEdmBJdecuuwDRL7uOEYrNh830WQ8
kis.api.app-secret=58whI+GQdnU4lIwSqQhFLrR7xm7stCyaOv/fDRdTo78PlKX1+2zuMpBbbV8BUAbcjK2GX8j6kwSqePK5AlaqvxjTNkrDq81HuKdRXeOUF07ahuaOKQV7o5pcA7wZMS32Cc0rSHHlmFCTRj7mjYqBh72n7yw+l3WJE2YbfB13iDEQvmucGsw=
kis.api.base-url=https://openapi.koreainvestment.com:9443

# DB (H2 ?? ????)
spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true